export const ASSIGNMENT_STATUS = {
  ASSIGNED: "ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const;

export const ASSIGNMENT_TARGET_TYPE = {
  VOLUNTEER: "VOLUNTEER",
  ORGANIZATION: "ORGANIZATION",
} as const;
